# Lab2B RP2040 Expansion Proposal

First, use GPIO to light up the LED, here's a brief .gif to show this:

<p align="center">
    <img src="assets\ezgif-3-0d3b8d071d.gif" width=25% height=25% />
</p>

## Proposal Outline
In our lab2, we want to build a logic gate with two RP2040, chip1 and chip2.
For chip1, we will use two GPIO of it as output and for chip2 we will use 2 GPIO of it as input and 1 GPIO as output.
In chip1, the program will prompt the user to select the output state for both output GPIO. 
This output state will display by a LED so that we can easily see whether the GPIO is in logic high or in logic low.
As for chip2, the 2 input GPIO will receive the logic state generated by chip1 and perform the logic operation. 
For example, if we want to build an AND gate, then the program in chip2 will perform logic AND, 
only when both input logic at high state will chip2 generate a high state to the output GPIO in chip2 and turn on the connected LED. 
Under all other cases, the LED connected to the output GPIO of chip2 will not be turned on.
We can do such programming to any Boolean function as we want, in such way we can build any logic gate we want.

**Components requested from Detkin Lab**:

- RP2040
- A half-size breadboard
- 2 break out cables
- One 330 Ohm resistor
- A LED
